name: "Integration Test"
on:
  workflow_dispatch:
jobs:
  integration-test:
    uses: "./.github/workflows/integration-test-with-version.yml"
    with:
      python-version: "${{ matrix.python-version }}"
    secrets: inherit
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
