name: "Pre-Commit Hooks"

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use. Supports SemVer as described in actions/setup-python." # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-input
        required: false
        type: string
        default: "3.13"
      ref:
        description: "The branch, tag or SHA to checkout."
        required: false
        type: string

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ inputs.ref }}

      - name: "Setup Python ${{ inputs.python-version }}"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ inputs.python-version }}"

      - name: "Install development dependencies"
        run: "pip install .[dev]"

      - name: "Install pre-commit hooks"
        run: "pre-commit install --install-hooks"

      - name: "Run pre-commit hooks"
        id: pre-commit
        run: "pre-commit run --color never --all-files > pre-commit-stdout"

      - name: "Summarize pre-commit hooks on failure"
        if: failure()
        run: |
          printf '### Pre-commit hooks\n\n```\n' > $GITHUB_STEP_SUMMARY
          cat pre-commit-stdout >> $GITHUB_STEP_SUMMARY
          printf '```\n\n### Applied fixes\n\n```diff\n' >> $GITHUB_STEP_SUMMARY
          git diff >> $GITHUB_STEP_SUMMARY
          printf '```\n' >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
