on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  build:
    uses: "./.github/workflows/build-package.yml"
    with:
      python-version: "3.13"
  release-please:
    needs: ["build"]
    runs-on: ubuntu-latest
    permissions:
      id-token:
        write # NOTE: Required for gh-action-pypi-publish, see
        # https://github.com/pypa/gh-action-pypi-publish/tree/release/v1?tab=readme-ov-file#:~:text=job%20with%20the-,id%2Dtoken%3A%20write,-permission%20and%20without
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - id: get-build-artifact
        name: "Get build artifact"
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: "dist/"
      - id: release-to-pypi
        name: "Release to PyPI"
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
      - id: add-artifact-to-release
        name: "Add artifact to release"
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./dist/*
