name: "Release Please"

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: "Release please"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      sha: ${{ steps.release.outputs.sha }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  build-and-publish:
    name: "Build and publish"
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: "Run pre-commit hooks"
        id: pre-commit-hooks
        uses: "./.github/workflows/pre-commit-hooks.yml"
        with:
          ref: ${{ needs.release-please.outputs.sha }}
      - name: "Build package"
        id: build
        uses: "./.github/workflows/build-package.yml"
        with:
          ref: ${{ needs.release-please.outputs.sha }}
      - name: "Download build artifact"
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact-name }}
          path: "dist/"
      - name: "Release to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: "Upload artifact to release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} ./dist/*
